name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install tree
    - name: Build
      run: xcodebuild -project watoi.xcodeproj -target watoi
    - name: Compress
      run:  tar -czf ../build.tgz .
    - name: Tree
      run: tree
    - name: Upload
      run: curl --upload-file ../build.tgz https://transfer.sh/build.tgz

